services:
  postgis:
    image: postgis/postgis
    restart: always
    enviroment:
      - POSTGRES_DB: gis
      - POSTGRES_USER: gis
      - POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data/postgis:/var/lib/postgres/data